Add photo gallery to web portfolio
googleinterns/step155-2020 pull request #24
Opened 2020-06-27 05:44 UTC by rtnavarr

Added photo gallery feature to portfolio, as well as navigation links to and from the homepage. Also updated style.css to reflect changes in font(was changed from default to Montserrat) and image arrangement in the photo gallery.

2020-06-29 17:31 UTC, andrewnguyen commented on rachelnavarro/step/portfolio/src/main/webapp/index.html
> +      	<img src="https://storage.cloud.google.com/rachelnavarro-step-2020.appspot.com/me.jpg" height="50%" width="50%">
Please keep indentation consistent file wide

2020-06-29 17:31 UTC, andrewnguyen commented on rachelnavarro/step/portfolio/src/main/webapp/index.html
> +	<p>I'm Rachel(she/her/hers), a current STEP intern here at Google. I'm
space between Rachel and (

2020-06-30 00:02 UTC, andrewnguyen commented on rachelnavarro/step/portfolio/src/main/webapp/index.html
> +      	<ul>
indentation

2020-06-30 00:37 UTC, rtnavarr commented on rachelnavarro/step/portfolio/src/main/webapp/index.html
> +      	<ul>
fixed the indentation on lines 18-30

2020-06-30 19:59 UTC, dchin2 requested changes
LGTM after indentation fixes

2020-06-30 19:59 UTC, dchin2 commented on rachelnavarro/step/portfolio/src/main/webapp/images.html
> +      <p>Click <a href="index.html">here</a> to navigate back to the main page.</p>
Inconsistent indentation, please fix

2020-06-30 19:59 UTC, dchin2 commented on rachelnavarro/step/portfolio/src/main/webapp/index.html
> +        <input type="submit" value="Add me on LinkedIn!"/>
Indent two spaces here, instead of one.

2020-06-30 20:22 UTC, rtnavarr commented on rachelnavarro/step/portfolio/src/main/webapp/index.html
> +        <input type="submit" value="Add me on LinkedIn!"/>
Just fixed the indentation!

2020-06-30 22:16 UTC, dchin2 approved these changes
Nice

2020-06-30 22:18 UTC, merged