Add comments feature and navigation bar with parallax scrolling
googleinterns/step155-2020 pull request #43
Opened 2020-07-07 18:26 UTC by rtnavarr

- Created a Comment class in Comment.java and modified DataServlet.java to store comments entered in an html form. 
- Modified script.js to fetch JSON/parse an array of comments from the /data server.
- Deleted hard-coded message display from the previous iteration of the week 3 walkthrough. 
- Modified index.html to display submitted comments in an unordered list.
- Created a navigation bar and added parallax and smooth scrolling.
- Updated comments and resolved merge conflicts.

2020-07-07 22:54 UTC, dchin2 requested changes

2020-07-07 22:54 UTC, dchin2 commented on rachelnavarro/step/portfolio/src/main/java/com/google/sps/data/Comment.java
> +    this.name = userName;
I would make these variable names the same, either userName or name.

2020-07-07 22:54 UTC, dchin2 commented on rachelnavarro/step/portfolio/src/main/webapp/script.js
> +      createCommentEntry(allcomments[i].name + ' said "' + allcomments[i].body + "' at " + datetime);
Are the quotes here correct?

I would use a format string, https://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format/32202320#32202320

It is easier to read :)

Something like \`${allComments[i].name} said "${allComments[i].body}" ... etc\`

Also rename allcomments to allComments.

2020-07-07 22:54 UTC, dchin2 commented on rachelnavarro/step/portfolio/src/main/webapp/script.js
> +  var datetime = today.getFullYear() + '-' + (today.getMonth()+1) + '-' + today.getDate() + " " + today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
same here with format string

2020-07-08 00:04 UTC, rtnavarr commented on rachelnavarro/step/portfolio/src/main/webapp/script.js
> +  var datetime = today.getFullYear() + '-' + (today.getMonth()+1) + '-' + today.getDate() + " " + today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
Fixed! @dchin2

2020-07-08 08:02 UTC, dchin2 approved these changes
lgtm after changes

2020-07-08 08:02 UTC, dchin2 commented on rachelnavarro/step/portfolio/src/main/webapp/script.js
>        var datetime = getDateTime();
change to dateTime, here and other places.

2020-07-08 16:20 UTC, merged